# Generated by Django 3.1.2 on 2020-10-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.CharField(default='Not downloaded yet', max_length=200),
        ),
    ]
